### ISSUE TITLE
Add a few jokes in Czech for Technical Computing Camp 2024

### ISSUE THREAD

**Issue by versionbaygt** [versionbaygt/MATLABJokes#5]

**Comment by versionbaygt** [comment]
Using ChatGPT:

"Můj software nikdy nemá chyby. Jen rozvíjí náhodné funkce."
"Moje heslo je posledních 16 číslic Pí."
"Řekl bych ti vtip o UDP, ale možná ho nepřijmeš."
"Máme-li kruhovou pizzu s poloměrem z a tloušťkou a, vypočítejte objem pizzy. pi*z*z*a."

**Comment by ares952** [comment]
Tenhle release je poslední. Žádný další nebude.

**Comment by versionbaygt** [comment]
> Tenhle release je poslední. Žádný další nebude.

Don't worry I will keep adding new languages and new releases. It depends also on how many times I give a talk about this and how many people want to contribute.

**Comment by ares952** [comment]
Thomas, it was supposed to be another czech joke in SW development.

**Comment by versionbaygt** [comment]
> Thomas, it was supposed to be another czech joke in SW development.

Ahhh phew, I feel much better. I will put it in:)

**Comment by versionbaygt** [comment]
@ares952  This is implemented in #34 and in release 0.6.1, just pushed.  see: https://nl.mathworks.com/matlabcentral/fileexchange/172039-jokes-in-matlab
